-
  environment:
    global:
      DOKAN_CI_CACHE: C:\dokan_ci_cache
      CYG_CACHE: '%DOKAN_CI_CACHE%\cygwin'
      MSYS2_CACHE: '%DOKAN_CI_CACHE%\msys2'
      CHOCO_CACHE: '%DOKAN_CI_CACHE%\choco'
      WLK_INST_CACHE: '%DOKAN_CI_CACHE%\wlk_inst'
      DOKAN_MAIN_BUILD_JOB_NAME: "Image: Visual Studio 2017; Configuration: All"

  version: 1.2.0-{build}
  configuration:
  - SonarQube

  image:
    - Visual Studio 2017
# If you suspect some changes on the AppVeyor-side breaking things,
# uncomment below. https://www.appveyor.com/updates/
#    - Previous Visual Studio 2015
#    - Previous Visual Studio 2017
  matrix:
    exclude:
      - configuration: SonarQube
        image: Visual Studio 2015
  max_jobs: 1
  cache:
  - '%DOKAN_CI_CACHE% -> appveyor.yml'

# To debug build issues, add your own fork to AppVeyor and uncomment below.
# Connection details will be printed to the console output.
# $blockRdp makes the build block until a file is deleted from the desktop.
#  init:
#    - ps: Invoke-Expression (Invoke-WebRequest 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1')
#  on_finish:
#    - ps: $blockRdp = $true; Invoke-Expression (Invoke-WebRequest 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1')

  install:
    - ps: |
        New-Item -ItemType Directory -Force -Path ${env:DOKAN_CI_CACHE} | Out-Null
    - ps: |
        function Exec-External {
          param(
            [Parameter(Position=0,Mandatory=1)][scriptblock] $command
          )
          & $command
          if ($LASTEXITCODE -ne 0) {
            throw ("Command returned non-zero error-code ${LASTEXITCODE}: $command")
          }
        }

  before_build:
  # Remove VS build warning http://help.appveyor.com/discussions/problems/4569-the-target-_convertpdbfiles-listed-in-a-beforetargets-attribute-at-c-does-not-exist-in-the-project-and-will-be-ignored
  #- del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"

  build_script:
  - ps: |
      Write-Host Start building...
      $buildCmd = $(cmd /c where msbuild)

  - ps: |
      if ($env:CONFIGURATION -eq "SonarQube") {
       
        if ($env:APPVEYOR_PULL_REQUEST_NUMBER) {
          Add-AppveyorMessage -Message "Not running SonarQube on pull request." -Category Information
          return;
        }
      
        Add-Type -assembly system.io.compression.filesystem
        choco install "sonarscanner-msbuild-net46" -y
        
        SonarScanner.MSBuild.exe begin /k:"godin-test-dokan" /v:$env:APPVEYOR_BUILD_VERSION /d:sonar.organization="godin-github" /d:sonar.cfamily.build-wrapper-output=bw-output /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login=$env:SONAR_TOKEN /d:sonar.cfamily.reproducer="C:/projects/dokany/dokan/dokan.c"
        
        Invoke-WebRequest https://sonarcloud.io/static/cpp/build-wrapper-win-x86.zip -OutFile .\build-wrapper-win-x86.zip
        & 7z e .\build-wrapper-win-x86.zip
               
        Invoke-Expression ".\build-wrapper-win-x86-64.exe --out-dir bw-output msbuild dokan.sln /m /p:Configuration='Win10 Debug' /p:Platform=x64"
        
        SonarScanner.MSBuild.exe end /d:sonar.login=$env:SONAR_TOKEN
      }

  on_finish:
  - ps: Push-AppveyorArtifact "C:\projects\dokany\sonar-cfamily.reproducer"
